### ISSUE TITLE
Bad Request - invalid nonce

### ISSUE THREAD

**Issue by zealot128** [gering/MoneyMoney-Bitcoin.de-Extension#1]
![Bildschirmfoto 2019-06-24 um 22 30 36](https://user-images.githubusercontent.com/147175/60049939-b9bbcc80-96cf-11e9-8213-80de5f3588b7.png)
![Bildschirmfoto 2019-06-24 um 22 30 26](https://user-images.githubusercontent.com/147175/60049940-ba546300-96cf-11e9-9680-3c382da1bd1d.png)

Auf bitcoin.de Protokoll gibt es jetzt diese Information:

![Bildschirmfoto 2019-06-24 um 22 29 54](https://user-images.githubusercontent.com/147175/60049893-9ee95800-96cf-11e9-8c1e-78135c7f7341.png)

Die nonce scheint zu klein zu sein.

Fix:

local nonce = MM.time() * 1000

**Comment by MagicChocoRolls** [comment]
Got the same problem.

**Comment by gering** [comment]
Now, I have a similar issue, since today. I'll have a closer look.
<img width="1335" alt="Screenshot 2020-04-01 at 09 34 55" src="https://user-images.githubusercontent.com/727981/78110911-1afd9280-73fc-11ea-8303-158f684e7a17.png">

**Comment by gering** [comment]
> Got the same problem.

You may need to login into your bitcoin.de account and accept new terms

<img width="1162" alt="Screenshot 2020-04-01 at 09 49 17" src="https://user-images.githubusercontent.com/727981/78120468-4d15f100-740a-11ea-81aa-a32a2dfdde27.png">

**Comment by MagicChocoRolls** [comment]
Ich wechsle mal auf deutsch, wenn's ok ist ;)

Habe mich vorher sogar bei Bitcoin.de eingeloggt, um einen neuen API Key zu erstellen. Die Fehlermeldung kam trotzdem.

Ich teste jetzt nochmal von vorne bis hinten durch.

by the way: Wieso gibt's im Code eigentlich einen statischen MD5 Wert? :)

**Comment by MagicChocoRolls** [comment]
Habe nichts anders gemacht. Selbe Key Permissions, selber Weg, keine neuen Bestimmungen akzeptiert...Funktioniert nun aber.
Danke für's nachschauen!
