### ISSUE TITLE
v2 nicht mehr supported

### ISSUE THREAD

**Issue by julien100** [gering/MoneyMoney-Bitcoin.de-Extension#3]
v2-API scheint nicht mehr zu funktionieren. Update auf v4 löst das Problem. 

`local apiBase = "https://api.bitcoin.de/v4/"`

**Comment by tobsen** [comment]
Der Fix funktioniert leider in der App-Store Version nicht, da man hier nicht die Signaturprüfung ausschalten kann.

**Comment by julien100** [comment]
Ja genau. Wenn musst du die BETA Version verwenden und dort kannst du die Signaturprüfung erst einmal ausschalten.

**Comment by gering** [comment]
Danke für den PR! Ich werde eine neue Version+Signatur erstellen.

**Comment by gering** [comment]
New version 1.2 available
