### ISSUE TITLE
bitcoin.de.lua:132: attempt to index field 'data' (a nil value)

### ISSUE THREAD

**Issue by rholighaus** [gering/MoneyMoney-Bitcoin.de-Extension#7]
Seit einiger Zeit funktioniert Bitcoin.de nicht mehr.
Kann ich dabei helfen, das zu debuggen?

**Comment by gering** [comment]
Ich habe keine Probleme mit der Extension, aber es gab auch schon Mail, die auf ein Problem hindeuten.

**Comment by rholighaus** [comment]
Hat sich erledigt - in der Tag musste ich mich mal "von Hand" auf der Website einloggen, dort den neuen AGBs zustimmen, seitdem funktioniert's wieder.
