### ISSUE TITLE
Fehlende USDT Unterstützung

### ISSUE THREAD

**Issue by thomasdingler** [gering/MoneyMoney-Bitcoin.de-Extension#8]
Seit ein paar Tagen kommt bei einem meiner Accounts immer diese Fehlermeldung:
**bitcoin.de.lua:113: attempt to concatenate field '?' (a nil value)**
Nach kurzer Prüfung der File vermute ich es liegt am fehlenden USDT Support.
<img width="443" alt="Screenshot 2024-05-21 at 09 29 18" src="https://github.com/gering/MoneyMoney-Bitcoin.de-Extension/assets/909744/abeabfb9-ef1d-496b-8652-be3fdb458977">

**Comment by gering** [comment]
Dieser [PR](https://github.com/gering/MoneyMoney-Bitcoin.de-Extension/pull/9) sollte dann das Problem lösen.

**Comment by thomasdingler** [comment]
Perfekt. Funktioniert. Danke!
